In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd
from geopandas import GeoDataFrame
import torch
import torch.nn as nn
import torch.optim as optim

In [11]:
input_tensor = torch.tensor([[0.2354, 0.3211, -0.4523, 0.2354, 0.3211, -0.8463]])                                                 
# create a 1x6 tensor with random values

In [12]:
model = nn.Sequential( nn.Linear(6,1),        # input layer                                     
                         nn.Linear(1,1))

In [13]:
#output

output_tensor = model(input_tensor)
print(output_tensor)

tensor([[-0.9222]], grad_fn=<AddmmBackward0>)


In [ ]:
#Create a netweork with 3  hidden layers    
model = nn.Sequential( 
    nn.Linear(6,10),
    nn.Linear(10,10),
    nn.Linear(10,5),
)

In [14]:
#Sigmoind activation function
input_tensor = torch.tensor([[6]])
sigmoid = nn.Sigmoid()   # create a sigmoid object
output_tensor = sigmoid(input_tensor)
print(output_tensor)

tensor([[0.9975]])


In [15]:
#Softmax activation function
input_tensor = torch.tensor([[4.3,6.1,2.3]])
probabilities = nn.Softmax(dim=-1)   # create a softmax object  
output_tensor = probabilities(input_tensor)
print(output_tensor)

tensor([[0.1392, 0.8420, 0.0188]])


In [16]:
#One hot encoding
import torch.nn.functional as F

print(F.one_hot(torch.tensor(0), num_classes=3))

tensor([1, 0, 0])


In [ ]:
#Cross entropy loss